#!/usr/bin/env bash

# Update NGINX configuration to listen on port 80
sed -i 's/listen 8080 default_server;/listen 80 default_server;/' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:8080 default_server ipv6only=on;/listen \[::\]:80 default_server;/' /etc/nginx/sites-enabled/default
sed -i 's/ ipv6only=on//' /etc/nginx/sites-available/default

# Restart NGINX service
service nginx restart
