#!/usr/bin/env bash
# This Script connects to the server 100.26.166.204 using the users private key
# stored in a file school Found in the users home directory
ssh -i ~/.ssh/school ubuntu@100.26.166.204
